### ISSUE TITLE
Support for Blender 3.2

### ISSUE THREAD

**Issue by beyond3dartist** [RxLaboratory/DuBlast#11]
Its still not support for Blender 3.2

**Comment by Nico-Duduf** [comment]
Yes it does, what's your issue exactly?

**Comment by Nico-Duduf** [comment]
There was a small issue in the latest release, that may be the problem you had.
Try with the new version (3.1.0) and let me know if that works!
-> https://rxlaboratory.org/tools/dublast-for-blender/
