### ISSUE TITLE
incrementation feature

### ISSUE THREAD

**Issue by LaMetabole** [RxLaboratory/DuBlast#6]
Hello,

It would be nice if there was a button "overwrite", to owerwrite the last file or increment automatically the new file.
Or, maybe easier : just a pop up "do you want to overwrite the last file ?"

Thanks in advance !

**Comment by Nico-Duduf** [comment]
As Blender automatically adds the frame range to the name, it makes incremented a bit too complicated, but instead I'm adding the date and time to the filename if you don't want to overwrite. Will be available in the update today ;)
